language: java

sudo: false

install: true

matrix:
  include:
  - jdk: openjdk8
  - jdk: oraclejdk8
    dist: trusty
  - jdk: openjdk11
  - jdk: openjdk12
  - jdk: openjdk13
  - jdk: openjdk-ea
  allow_failures:
  - jdk: openjdk-ea

script: mvn clean verify -B -V -U

cache:
  directories:
  - $HOME/.m2
